baseURL: https://blitzortung.tryb.de/
title: My New Hugo Site
theme: book
title: "Blitzortung Lightning Monitor"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
#    - JSON
#
languages:
  en:
    disabled: false
    params:
      languageCode: en-us
      languageName: English
  de:
    disabled: false
    params:
      langageCode: de-de
      languageName: Deutsch
