baseURL: https://blitzortung.tryb.de/
title: "Blitzortung Lightning Monitor"
theme: book

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
#    - JSON
#
languages:
  en:
    contentDir: content/en
    disabled: false
    languageName: English
    params:
      languageCode: en-us
  de:
    contentDir: content/de
    disabled: false
    languageName: Deutsch
    title: "Blitzortung Gewitter Monitor"
    params:
      langageCode: de-de
